export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    //top bar
    "_yourContry": "Your Contry",
    '_login': 'Login',
    '_registration': 'Registartion',
    '_busket': 'Busket',
    '_enter_request': 'Enter request',
    '_call_back': 'Request a call back',
    '_for_the_sum': 'for the sum of',
    '_name': 'Name',
    '_article': 'Article',
    '_show_all': 'Show all',
    //home
    '_subscribe_text': 'SUBSCRIBE TO NEWS, PROMOTIONS AND DISCOUNTS',
    '_subscribe': 'Subscribe',
    '_join': 'JOIN',
    '_social_media': 'Us on social media',
    '_fast_delivery': 'FAST DELIVERY',
    '_individual_approach': 'Individual approach',
    '_payment_method': 'Convenient payment method',
    '_quality': 'original quality',
    'error1': 'This is a required field',
    'error2': 'Enter a valid email',
    'success': 'Thank you you have successfully subscribed',
    'brands': 'Brands',

    //footer
    '_about_company': 'About Company',
    '_products_catalog': 'PRODUCT CATALOG',
    'contacts': 'Contacts',
    //slide-nav
    '_info': 'Information',
    '_catalog': 'Catalog',
    //busket
    '_get_sale': 'Get sale',
    '_pack_text': 'Pack in gift box',
    '_total': 'TOTAL',
    '_order': 'To do order',
    '_pack_sum': 'RUB to order',
    '_contact_entity': 'Contact details',
    '_full_name': 'Full Name',
    '_phone': 'Phone',
    '_necessarily': 'necessarily',
    '_email': 'E-mail',
    '_main_addresses': 'Main addresses',
    '_city': 'City',
    '_address': 'Address',
    '_index': 'Index',
    '_comment': 'Commnets',
    '_not': 'not',
    '_delivery_method': 'Delivery method',
    'payment_method': 'Payment method',
    '_inner_balance': 'Inner balance',
    '_from_balance': 'From balance',
    '_your_balance': 'Your balance',
    '_payment_error': 'Your balance is insufficient for payment',
    '_bonus_error': 'Your bonus is not enough to pay ',
    '_with_bonus': 'With a bonus',
    '_your_bonus': 'Your bonus',
    '_order_sum': 'ORDER AMOUNT',
    '_delivery': 'DELIVERY',
    '_insurance': 'INSURANCE PREMIUM',
    '_commission': 'COMMISSION',
    '_total_text': 'TOTAL TO BE PAID ON THE SPOT',
    '_total_pay_now':'TOTAL PAYMENT DUE NOW',
    '_empty_busket':'Your busket is empty',
    '_select' : 'Select',
    '_your_city':'Your city',
    '_remember':'Remember',
    '_enter':'Enter',
    '_recover_password':'Recover the password',
    //registration
    '_password':'Password',
    '_confirm_password':'Confirm password',
    '_password_error':'Passwords do not match',
    '_your_name':'Your name',
    '_phone_number':'Phone number',
    
    
};