export const LANG_ARM_NAME = 'arm';

export const LANG_ARM_TRANS = {

    //top bar
    "_yourContry": "Ձեր քաղաքը",
    '_login': 'Մուտք',
    '_registration': 'Գրանցում',
    '_busket': 'Զամբյուղ',
    '_enter_request': 'Մուտքագրեք հարցումը',
    '_call_back': 'Պատվիրել հետադարձ զանգ',
    '_for_the_sum': 'գումարով',
    '_name': 'Անուն',
    '_article': 'Արտիկուլ',
    '_show_all': 'Ցույց տալ բոլորը',
    //home
    '_subscribe_text': ' ՆՈՐՈՒԹՅՈՒՆՆԵՐԻ, ԱԿՑԻԱՆԵՐԻ ԵՒ ԶԵՂՉԵՐԻ ԲԱԺԱՆՈՐԴԱԳՐՈՒԹՅՈՒՆ',
    '_subscribe': ' ԲԱԺԱՆՈՐԴԱԳՐՎԵԼ',
    '_join': 'Միացեք',
    '_social_media': 'Մեզ սոցիալական ցանցերում',
    '_fast_delivery': 'ԱՐԱԳ ԱՌԱՔՈՒՄ',
    '_individual_approach': 'Անհատական մոտեցում',
    '_payment_method': 'Հարմար վճարման եղանակը',
    '_quality': 'Օրիգինալ որակ',
    'error1': 'Սա պարտադիր դաշտ է',
    'error2': 'Մուտքագրեք ճիշտ email',
    'success': 'Շնորհակալություն դուք հաջողությամբ բաժանորդագրված եք',
    '_about_company': 'ԸՆԿԵՐՈՒԹՅԱՆ ՄԱՍԻՆ',
    '_products_catalog': 'ԱՊՐԱՆՔՆԵՐԻ ԿԱՏԱԼՈԳ',
    'contacts': 'Կոնտակտներ',
    'brands': 'Ապրանքանշաններ',
    //slide-nav
    '_info': 'Տեղեկատվություն',
    '_catalog': 'ԿԱՏԱԼՈԳ',
    //busket
    '_get_sale': 'Ստանալ զեղչ',
    '_pack_text': 'Փաթեթավորեք նվերի փաթեթավորմամբ',
    '_total': 'ԸՆԴԱՄԵՆԸ',
    '_order': 'Պատվիրել',
    '_pack_sum': 'ռուբլի պատվերին',
    '_contact_entity': 'Կոնտակտային տվյալներ',
    '_full_name': 'Անունը',
    '_phone': 'Հեռախոսահամար',
    '_necessarily': 'պարտադիր',
    '_email': 'Էլ․հասցե',
    '_main_addresses': 'Հիմնական հասցեները',
    '_city': 'Քաղաք',
    '_address': 'Հասցե',
    '_index': 'Ինդեքս',
    '_comment': 'Մեկնաբանություն',
    '_not': 'ոչ',
    '_delivery_method': 'Առաքման եղանակը',
    'payment_method': 'Վճարման եղանակը',
    '_inner_balance': 'Ներքին հաշվեկշիռ',
    '_from_balance': 'Բալանսից',
    '_your_balance': 'Ձեր բալանսը',
    '_payment_error': 'Ձեր հաշվեկշիռը բավարար չէ վճարման համար',
    '_bonus_error': 'Ձեր բոնուսը բավարար չէ վճարման համար',
    '_with_bonus': 'Բոնուսներով',
    '_your_bonus': 'Ձեր բոնուսը',
    '_order_sum': 'ՊԱՏՎԵՐԻ ԳՈՒՄԱՐԸ',
    '_delivery': 'ԱՌԱՔՈՒՄ',
    '_insurance': 'ԱՊԱՀՈՎԱԳՐԱԿԱՆ ՎՃԱՐ',
    '_commission':'ՀԱՆՁՆԱԺՈՂՈՎ',
    '_total_text':'ՏԵՂՈՒՄ ՎՃԱՐՄԱՆ ՀԱՄԱՐ ԸՆԴԱՄԵՆԸ',
    '_total_pay_now':'ՀԻՄԱ ՎՃԱՐՄԱՆ ՀԱՄԱՐ ԸՆԴԱՄԵՆԸ',
    '_empty_busket':'Ձեր զամբյուղը դատարկ է',
    '_select' : 'Ընտրել',
    '_your_city':'Ձեր քաղաքը',
    '_remember':'Հիշել',
    '_enter':'Մուտք',
    '_recover_password':'Վերականգնել գաղտնաբառը',
    '_password':'Գաղտնաբառ',
    '_confirm_password':'Հաստատել գաղտնաբառը',
    '_password_error':'Գաղտնաբառերը չեն համընկնում',
    '_your_name': 'Ձեր անունը',
    '_phone_number': 'Հեռախոսահամարը',


};