export const LANG_RU_NAME = 'ru';

export const LANG_RU_TRANS = {
    "_yourContry": "Ваш город",
    '_login': 'Вход',
    '_registration': 'Регистрация',
    '_busket': 'Корзина',
    '_enter_request': 'Введите запрос',
    '_call_back': 'Заказать обратный звонок',
    '_for_the_sum': 'на сумму',
    '_subscribe_text': 'ПОДПИСКА НА НОВОСТИ, АКЦИИ И СКИДКИ',
    '_subscribe': ' ПОДПИСАТЬСЯ',
    '_join': 'ПРИСОЕДИНЯЕТЕСЬ',
    '_social_media': 'К нам в социальных сетях',
    '_name': 'Имя',
    '_article': 'Артикул',
    '_show_all': 'Показать все',
    '_fast_delivery': 'БЫСТРАЯ ДОСТАВКА',
    '_individual_approach': ' Индивидуальный подход',
    '_payment_method': 'Удобный способ оплаты',
    '_quality': 'оригинальное качество',
    'error1': 'Это обязательное поле',
    'error2': 'Введите правильный email',
    'success': 'Спасибо Вы успешно подписаны !',
    '_about_company': 'О КОМПАНИИ',
    '_products_catalog': 'КАТАЛОГ ТОВАРОВ',
    'contacts': 'КОНТАКТЫ',
    'brands': 'Бренды',
    '_info': 'ИНФОРМАЦИЯ',
    '_catalog': 'КАТАЛОГ',
    '_get_sale': 'Получить скидку',
    '_pack_text': 'Упаковать в подарочную упаковку',
    '_total': 'ИТОГО',
    '_order': 'Оформить заказ',
    '_pack_sum': 'руб к заказу',
    '_contact_entity': 'Контактные данные',
    '_full_name': 'ФИО',
    '_phone': 'Телефон',
    '_necessarily': 'обязательно',
    '_email': 'E-mail',
    '_main_addresses': 'Основные адреса',
    '_city': 'Город',
    '_address': 'Адрес',
    '_index': 'Индекс',
    '_comment': 'Комментарий',
    '_not': 'не',
    '_delivery_method': 'Способ доставки',
    'payment_method': 'Способ оплаты',
    '_inner_balance': 'Внутренний баланс',
    '_from_balance': 'Из баланса',
    '_your_balance': 'Ваш баланс',
    '_payment_error': 'Ваш баланс недостаточен для оплаты',
    '_bonus_error': 'Вашего бонуса недостаточно для оплаты',
    '_with_bonus': 'С бонусами',
    '_your_bonus': ' Ваш бонус',
    '_order_sum': 'СУММА ЗАКАЗА',
    '_delivery': 'ДОСТАВКА',
    '_insurance': 'СТРАХОВОЙ ВЗНОС',
    '_commission': 'КОМИССИЯ',
    '_total_text': 'ИТОГО К ОПЛАТЕ НА МЕСТЕ',
    '_total_pay_now': 'ИТОГО К ОПЛАТЕ СЕЙЧАС',
    '_empty_busket': 'Ваша корзина пуста',
    '_select': 'Выбрать',
    '_your_city': 'Ваш город',
    '_remember': 'Запомнить',
    '_enter': 'Войти',
    '_recover_password': 'Восстановить пароль',
    '_confirm_password': 'Подтвердить пароль',
    '_password': 'Пароль',
    '_password_error': 'Пароли не совпадают',
    '_your_name': 'Ваше имя',
    '_phone_number': 'Номер телефона',

};